-- 个人设置（settings.reader.lua 补丁）：以掌阅上的设置为准，所有设备共用（用户 2026-09-28 定）。
-- 来源：2026-09-28 掌阅 settings.reader.lua 里、跟 KOReader 缺省不同的全部个人项——排版（copt_*、正文字体，10-02 换成霞鹜新晰黑＋）、
-- 页眉（cre_header_*）、状态栏（footer）、中文排版微调（style_tweaks）、停用的插件、返回键行为、启动进文件管理器等。
-- 不在这里的：随设备的路径和标识（devices/<id>/）、状态栏字体的文件路径（devices/<id>/）、文字书方案（schemes/）。
-- 在设备上改了个人设置、想让另一台也跟上：改这里再对两台各跑一次 apply.sh。
-- 语义见 merge.lua：标量覆盖、表递归、"__DELETE__" 删键。正文字体要设备上装了才生效（见 docs/koreader.md「字体」）。
return {
    -- 界面字体（菜单、按键、标题、提示、状态栏里的文字）：霞鹜新晰黑＋（用户 2026-10-02 从文楷 Medium 换过来；状态栏的京華老宋体不变）。
    -- KOReader 菜单里没有这个设置，但启动时会读 settings.reader.lua 的 fontmap 覆盖 frontend/ui/font.lua 里写死的
    -- Font.fontmap（reader.lua「User fonts override」，在界面管理器加载之前）。只写文件名，Font:getFace 先找 KOReader 的
    -- fonts/，找不到再搜所有字体目录。等宽的几项（scfont 快捷键、hpkfont 按键帮助、infont 输入框、smallinfont 代码）不换：
    -- 新晰黑不是等宽，换了对不齐。字体文件不在时 KOReader 会退回缺省字体。
    ["fontmap"] = {
        ["cfont"] = "LXGWNeoXiHeiPlus.ttf",
        ["tfont"] = "LXGWNeoXiHeiPlus.ttf",
        ["smalltfont"] = "LXGWNeoXiHeiPlus.ttf",
        ["x_smalltfont"] = "LXGWNeoXiHeiPlus.ttf",
        ["ffont"] = "LXGWNeoXiHeiPlus.ttf",
        ["smallffont"] = "LXGWNeoXiHeiPlus.ttf",
        ["largeffont"] = "LXGWNeoXiHeiPlus.ttf",
        ["rifont"] = "LXGWNeoXiHeiPlus.ttf",
        ["pgfont"] = "LXGWNeoXiHeiPlus.ttf",
        ["hfont"] = "LXGWNeoXiHeiPlus.ttf",
        ["infofont"] = "LXGWNeoXiHeiPlus.ttf",
        ["smallinfofont"] = "LXGWNeoXiHeiPlus.ttf",
        ["smallinfofontbold"] = "LXGWNeoXiHeiPlus.ttf",
        ["x_smallinfofont"] = "LXGWNeoXiHeiPlus.ttf",
        ["xx_smallinfofont"] = "LXGWNeoXiHeiPlus.ttf",
    },
    ["autowarmth_fl_off_during_day"] = true,
    ["back_in_filemanager"] = "default",
    ["back_in_reader"] = "previous_location",
    ["back_to_exit"] = "prompt",
    ["color_rendering"] = false,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_css"] = "./data/epub.css",
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 17,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 2,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_font"] = "LXGW Neo XiHei Plus", -- 正文字体：霞鹜新晰黑＋（用户 2026-10-02 从文楷换过来；名字是字体文件里的字体族名）
    ["cre_header_battery_percent"] = 1,
    ["cre_header_chapter_marks"] = 0,
    ["cre_header_page_count"] = 0,
    ["cre_header_page_number"] = 0,
    ["cre_header_reading_percent"] = 1,
    ["cre_header_status_font_size"] = 27,
    ["default_highlight_action"] = "ask",
    ["dimension_units"] = "mm",
    ["footer"] = {
        ["align"] = "center",
        ["all_at_once"] = true,
        ["auto_refresh_time"] = false,
        ["battery"] = false,
        ["battery_hide_threshold"] = 100,
        ["book_author"] = false,
        ["book_author_max_width_pct"] = 30,
        ["book_chapter"] = false,
        ["book_chapter_max_width_pct"] = 30,
        ["book_time_to_read"] = true,
        ["book_title"] = false,
        ["book_title_max_width_pct"] = 30,
        ["bookmark_count"] = false,
        ["bottom_horizontal_separator"] = false,
        ["chapter_progress"] = false,
        ["chapter_progress_bar"] = false,
        ["chapter_time_to_read"] = true,
        ["container_bottom_padding"] = 1,
        ["container_height"] = 14,
        ["disable_progress_bar"] = false,
        ["disabled"] = false,
        ["frontlight"] = false,
        ["hide_empty_generators"] = false,
        ["initial_marker"] = false,
        ["invert_progress_direction"] = false,
        ["item_prefix"] = "icons",
        ["items_separator"] = "bar",
        ["lock_tap"] = true,
        ["mem_usage"] = true,
        ["order"] = {
            [0] = "off",
            [1] = "page_progress",
            [2] = "pages_left",
            [3] = "chapter_time_to_read",
            [4] = "book_time_to_read",
            [5] = "mem_usage",
            [6] = "additional_content",
            [7] = "pages_left_book",
            [8] = "time",
            [9] = "battery",
            [10] = "frontlight",
            [11] = "wifi_status",
            [12] = "book_title",
            [13] = "book_chapter",
            [14] = "bookmark_count",
            [15] = "chapter_progress",
            [16] = "percentage",
            [17] = "custom_text",
            [18] = "book_author",
            [19] = "page_turning_inverted",
            [20] = "dynamic_filler",
            [21] = "dynamic_filler2",
        },
        ["page_progress"] = true,
        ["page_turning_inverted"] = false,
        ["pages_left"] = true,
        ["pages_left_book"] = false,
        ["pages_left_includes_current_page"] = false,
        ["percentage"] = false,
        ["progress_bar_min_width_pct"] = 20,
        ["progress_bar_position"] = "alongside",
        ["progress_margin"] = false,
        ["progress_margin_width"] = 32,
        ["progress_pct_format"] = "2",
        ["progress_style_thick_height"] = 7,
        ["progress_style_thin"] = false,
        ["progress_style_thin_height"] = 3,
        ["reclaim_height"] = false,
        ["skim_widget_on_hold"] = false,
        ["text_font_bold"] = false,
        ["text_font_size"] = 15,
        ["time"] = false,
        ["toc_markers"] = true,
        ["toc_markers_width"] = 2,
        ["wifi_status"] = false,
    },
    ["ges_tap_interval_ms"] = 500,
    ["ges_tap_interval_on_keyboard_ms"] = 0,
    ["inertial_scroll"] = false, -- 惯性滚动关（用户 2026-09-29：照 Kindle 上的，两台都关）
    ["keyboard_key_font_size"] = 22,
    ["lock_rotation"] = true,
    ["low_pan_rate"] = true,
    ["night_mode"] = false,
    -- 停用的插件（用户 2026-10-02：关掉用不到的，菜单清爽、启动少加载）。留着的：autosuspend（闲置自动休眠）、autowarmth（按时间调暖光）、
    -- coverbrowser（封面浏览，2-browser-folder-cover 补丁靠它）、gestures、kosync（进度同步）、statistics（状态栏的剩余时间靠它）、
    -- vocabbuilder（查过的词做成生词本）；hotkeys 只在 Kindle 上停（掌阅有翻页键，见 devices/）。
    ["plugins_disabled"] = {
        ["archiveviewer"] = true,      -- 浏览 zip
        ["autodim"] = true,            -- 闲置时调暗前光：和自动前光打架
        ["autostandby"] = true,        -- Kobo 的待机
        ["autoturn"] = true,
        ["batterystat"] = true,
        ["bookshortcuts"] = true,
        ["calibre"] = true,
        ["cloudstorage"] = true,
        ["coverimage"] = true,
        ["docsettingtweak"] = true,
        ["exporter"] = true,
        ["externalkeyboard"] = true,
        ["hello"] = true,
        ["httpinspector"] = true,
        ["japanese"] = true,
        ["keepalive"] = true,
        ["movetoarchive"] = true,
        ["newsdownloader"] = true,
        ["opds"] = true,               -- 书用 USB 拷
        ["perceptionexpander"] = true,
        ["profiles"] = true,           -- 漫画配置档没恢复，用不到
        ["qrclipboard"] = true,
        ["readtimer"] = true,
        ["SSH"] = true,                -- Kindle 版自带；不用
        ["systemstat"] = true,
        ["terminal"] = true,
        ["texteditor"] = true,
        ["wallabag"] = true,
    },
    ["reader_footer_mode"] = 1,
    ["show_hidden"] = true,
    -- 界面语言简体中文：Kindle 上 KOReader 缺省跟系统（英文）（用户 2026-09-29）
    ["language"] = "zh_CN",
    ["style_tweaks"] = {
        ["cjk_tailored"] = true,
        ["footnote-inpage_fb2"] = true,
        ["paragraph_whitespace_half"] = true,
        ["pure_black_and_white"] = true,
    },
    ["twelve_hour_clock"] = true,
}
