-- SimpleUI 插件的设置（settings/simpleui/sui_settings.lua 补丁；插件 simpleui.koplugin v2.7.1，MIT，
-- https://github.com/doctorhetfield-cmd/simpleui.koplugin）。属于个人设置：两台统一，--uninstall 不撤。
-- 2026-09-29 从掌阅上用户调好的设置收进来（主页模块与顺序、底栏、顶栏、快捷设置栏）；不收插件自己的状态
-- （simpleui_loaded_version、*_migrated*、simpleui_streak_*：各设备各记各的）。在掌阅上改了想同步：重新收一遍。
-- 省电约定（用户 2026-09-29）：不要每分钟刷新的时钟——主页时钟模块关（simpleui_hs_clock_enabled = false）、
-- 顶栏 clock = "hidden"。顶栏配置要整张写全：只写 clock 一项，插件会把没写的电池、Wi-Fi 也当隐藏。
-- simpleui_updater_auto_check = true 是用户自己开的（插件每 24 小时联网查一次 GitHub 上的新版本）。
return {
    ["simpleui_bar_enabled"] = true,
    ["simpleui_bar_mode"] = "both",
    ["simpleui_bar_tabs"] = {
        [1] = "home",
        [2] = "sui_settings",
        [3] = "homescreen",
        [4] = "history",
        [5] = "power",
    },
    ["simpleui_browsemeta_enabled"] = true,
    ["simpleui_enabled"] = true,
    ["simpleui_fc_cover_mode"] = "2_3",
    ["simpleui_fc_enabled"] = true,
    ["simpleui_fc_folder_style"] = "auto",
    ["simpleui_fc_subfolder_cover"] = true,
    ["simpleui_home_key_opens_hs"] = true,
    ["simpleui_hs_action_list_enabled"] = false,
    ["simpleui_hs_clock_battery"] = false,
    ["simpleui_hs_clock_date"] = false,
    ["simpleui_hs_clock_enabled"] = false,
    ["simpleui_hs_collections_enabled"] = false,
    ["simpleui_hs_coverdeck_enabled"] = false,
    ["simpleui_hs_coverdeck_main_order"] = {
        [1] = "covers",
        [2] = "title",
        [3] = "author",
        [4] = "progress",
        [5] = "stats",
    },
    ["simpleui_hs_coverdeck_show_author"] = false,
    ["simpleui_hs_coverdeck_show_book_days"] = false,
    ["simpleui_hs_coverdeck_show_book_remaining"] = false,
    ["simpleui_hs_coverdeck_show_book_time"] = false,
    ["simpleui_hs_coverdeck_show_percent"] = true,
    ["simpleui_hs_coverdeck_show_progress"] = true,
    ["simpleui_hs_coverdeck_show_stats"] = true,
    ["simpleui_hs_coverdeck_show_title"] = true,
    ["simpleui_hs_currently_bar_style"] = "with_pct",
    ["simpleui_hs_currently_enabled"] = true,
    ["simpleui_hs_currently_show_author"] = true,
    ["simpleui_hs_currently_show_book_days"] = true,
    ["simpleui_hs_currently_show_book_remaining"] = true,
    ["simpleui_hs_currently_show_book_time"] = true,
    ["simpleui_hs_currently_show_description"] = true,
    ["simpleui_hs_currently_show_percent"] = false,
    ["simpleui_hs_currently_show_progress"] = true,
    ["simpleui_hs_currently_show_series"] = false,
    ["simpleui_hs_currently_show_title"] = true,
    ["simpleui_hs_currently_stats_style"] = "compact",
    ["simpleui_hs_module_order"] = {
        [1] = "quote",
        [2] = "currently",
        [3] = "recent",
        [4] = "clock",
        [5] = "coverdeck",
        [6] = "new_books",
        [7] = "tbr",
        [8] = "collections",
        [9] = "reading_goals",
        [10] = "reading_stats",
        [11] = "quick_actions_row_000001",
        [12] = "quick_actions_row_000002",
        [13] = "quick_actions_row_000003",
        [14] = "action_list",
    },
    ["simpleui_hs_new_books_enabled"] = false,
    ["simpleui_hs_quick_actions_row_000001_enabled"] = false,
    ["simpleui_hs_quick_actions_row_000002_enabled"] = false,
    ["simpleui_hs_quick_actions_row_000003_enabled"] = false,
    ["simpleui_hs_quote_enabled"] = false,
    ["simpleui_hs_reading_goals_enabled"] = false,
    ["simpleui_hs_reading_stats_enabled"] = false,
    ["simpleui_hs_recent_enabled"] = true,
    ["simpleui_hs_recent_show_finished"] = true,
    ["simpleui_hs_tbr_enabled"] = false,
    ["simpleui_onboarding_done"] = true,
    ["simpleui_qa_list"] = {},
    ["simpleui_qa_row_instances"] = {
        [1] = "quick_actions_row_000001",
        [2] = "quick_actions_row_000002",
        [3] = "quick_actions_row_000003",
    },
    ["simpleui_qs_bar_bg"] = "flat",
    ["simpleui_qs_bar_enabled"] = true,
    ["simpleui_qs_bar_frontlight"] = false,
    ["simpleui_qs_bar_settings_on_hold"] = true,
    ["simpleui_qs_bar_shape"] = "round",
    ["simpleui_qs_bar_slots"] = {
        [1] = "wifi_toggle",
        [2] = "bookmark_browser",
        [3] = "frontlight",
        [4] = "night_mode",
        [5] = "power",
        [6] = "sui_settings",
    },
    ["simpleui_qs_bar_warmth"] = false,
    ["simpleui_reading_goals_show_annual"] = true,
    ["simpleui_reading_goals_show_daily"] = false,
    ["simpleui_reading_goals_show_monthly"] = false,
    ["simpleui_tb_fm_cfg"] = {
        ["order_left"] = {
            [1] = "fm_back",
            [2] = "fm_search",
        },
        ["order_right"] = {
            [1] = "fm_browse",
            [2] = "fm_menu",
        },
        ["side"] = {
            ["fm_back"] = "left",
            ["fm_browse"] = "right",
            ["fm_menu"] = "right",
            ["fm_search"] = "left",
        },
    },
    ["simpleui_tb_item_fm_browse"] = true,
    ["simpleui_tb_item_fm_search"] = true,
    ["simpleui_topbar_config"] = {
        ["order_left"] = {
            [1] = "clock",
        },
        ["order_right"] = {
            [1] = "wifi",
            [2] = "battery",
        },
        ["side"] = {
            ["battery"] = "right",
            ["clock"] = "hidden",
            ["wifi"] = "right",
        },
    },
    ["simpleui_topbar_enabled"] = true,
    ["simpleui_updater_auto_check"] = true,
}
